name: Build And Upload Image For Wordpress-sqlite

on:
  push:
    branches:
      - main
    paths:  # 仅当 wordpress-sqlite/ 目录下的文件发生更改时触发
      - 'wordpress-sqlite/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 QEMU（用于多平台构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 设置 Docker Buildx（用于多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到 Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 提取版本信息
      - name: Extract Version
        run: |
          echo VERSION_TAG=latest >> $GITHUB_ENV

      # 构建并推送 Docker 镜像
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: wordpress-sqlite/Dockerfile  # 指定 Dockerfile 路径
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ secrets.DOCKER_USER_NAME }}/wordpress-sqlite:${{ env.VERSION_TAG }}